<div class="auth-container">
  <div class="auth-header">
    <h1 class="login">Login</h1>
    <a [routerLink]="['/signup']">
      <h1 class="signup">Register</h1>
    </a>
  </div>

  <form (ngSubmit)="submitForm(form)" #form="ngForm" novalidate [ngClass]="{'is-processing': processing}" class="auth-form">

    <div class="field" [ngClass]="{'has-error': usernameField.errors}">
      <input type="text" name="username" [(ngModel)]="username" #usernameField="ngModel" required [disabled]="processing" placeholder="username"
      />
      <div *ngIf="usernameField.errors && (usernameField.dirty || usernameField.touched)">
        <p class="error" [hidden]="!usernameField.errors.required" [ngClass]="{'has-error': feedbackEnabled}">
          Wrong username
        </p>
      </div>
    </div>

    <div class="field" [ngClass]="{'has-error': passwordField.errors}">
      <input type="password" name="password" [(ngModel)]="password" #passwordField="ngModel" required [disabled]="processing" placeholder="password"
      />
      <div *ngIf="passwordField.errors && (passwordField.dirty || passwordField.touched)">
        <p class="error" [hidden]="!passwordField.errors.required" [ngClass]="{'has-error': feedbackEnabled}">
          Wrong password
        </p>
      </div>
    </div>

    <div *ngIf="error" class="validation">
      <div [ngSwitch]="error.code">
        <p *ngSwitchCase="'not-found'"> Wrong username or password</p>
        <p *ngSwitchDefault> unexpected error occured, try again later</p>
      </div>
    </div>

    <div class="field-submit">
      <button class="submit" type="submit" [disabled]="processing"> Login </button>
    </div>
  </form>
</div>